### ISSUE TITLE
Isn't working! license_eval_halcon_progress_2024_12.dat

### ISSUE THREAD

**Issue by Puneethur** [lovelyyoshino/Halcon_licenses#30]
Please help to upload working eval halcon license of December 2024(Both Steady and Progress) for halcon12, 13, 18 and 22 development.

Thank you in advance..

**Comment by lovelyyoshino** [comment]
you can see halcon12, 13, 18 and 22 development.

**Comment by ikeriparraguirre** [comment]
Hi guys!
I've been investigating for a while because today I’ve downloaded the licenses, and when I tried to run Halcon 13.0.2.2, it didn’t work.
After reviewing several posts on the 51Halcon forum, it seems that the evaluation licenses are no longer compatible with older versions of Halcon (or at least that’s what I’ve understood).
In this post, they explain the issue in more detail (although the translation isn’t very clear):
Link to the post: https://www.51halcon.com/forum.php?mod=viewthread&tid=7178
Following the recommendations, I’ve decided to install one of the latest versions of Halcon. I’ve downloaded the executable from the official Halcon website, following the tutorial mentioned in the forum:
Link to the tutorial: https://www.51halcon.com/forum.php?mod=viewthread&tid=7258
Once I’ve loaded the licenses into the license folder of the new version, everything has worked correctly.
However, I still haven’t been able to get Halcon 13.0.2.2 to work with the new licenses. Has anyone managed to get this version working?

**Comment by Delphi4Ever** [comment]
You cannot use anymore those licenses for old HDEVELOPs, only for new ones. They works only for demo in runtimes environments.

**Comment by lovelyyoshino** [comment]
You cannot use anymore those licenses for old HDEVELOPs, only for new ones. They works only for demo in runtimes environments.

**Comment by lovelyyoshino** [comment]
Only 24.05, 24.11, not listed versions are no longer supported

**Comment by wonderballRyan** [comment]
My version is 22.11,so it means we cannot use these old versions any more?

**Comment by ikeriparraguirre** [comment]
Not with the evaluation licence, you need to buy an official licence.

**Comment by anewworl** [comment]
oh hi @ikeriparraguirre, I wonder with the latest versions of Halcon (24.11) which file do you use do you still remember the name of it or you just load all of the license in ?

**Comment by ikeriparraguirre** [comment]
hi @anewworl , I usually copy all my files to the licenses folder.

**Comment by Helloiamwin** [comment]
key 05.2025 does not work Halcon ver 24

**Comment by Maurits2014** [comment]
> key 05.2025 does not work Halcon ver 24

Same, 24.05 does not work, but 24.11 perhaps does. Unfortunately I cannot upgrade yet.
